title: Datatables
description: PHP Library to handle server-side processing for Datatables, in a fast and simple way.
google_analytics: UA-6840871-6
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
